# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to retrieve a BGS simulation sample

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            AllowOrigin: "'*'"

Resources:
    RetrieveBgsSimulationSampleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: bgs-retrieve-simulation-sample.default
            Runtime: nodejs10.x
            Timeout: 180
            MemorySize: 128
            CodeUri: ./dist/bgs-retrieve-simulation-sample
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-bgs-simulation-sample
            Events:
                GetMatchStatsResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    RetrieveBgsSimulationSampleApi:
        Description: URL to retrieve a BGS simulation sample
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
        Export:
            Name: RetrieveBgsSimulationSampleApi
